#
#  Configuration file for BitWave Bio
#     https://github.com/BitWaveOrg
#

user_firstname: 'SmookyWizard' # Username shown on profile (Required)
userbio: 'Лев — это твоя жадная душа, а лиса — это дьявол, вводящий тебя в заблуждение.' # Profile description (Required)

linkedin_login: '' # LinkedIn login (Optional)
telegram_login: '' # Telegram login (Optional)
discords_login: '' # DiscordS login (Optional)
steam_login: 'zopronyt' # SteamCommunity ID (Optional)
instagram_login: 'chuk.one' # Instagram login (Optional)
twitter_login: '' # Twitter login (Optional)
website_url: 'https://chuk.cz' # Website url (Optional)
cv_url: '' # CV URL (Optional)

profile_theme: 'dark' # Profile style
profile_color: 'rgb(32, 34, 37)' # Profile border color
