#
#  Configuration file for BitWave Bio
#     https://github.com/BitWaveOrg
#

user_firstname: 'wzrd.' # Username shown on profile (Required)
userbio: 'I am engaged in the development of bots for the discord platform as well as the creation of websites of varying complexity' # Profile description (Required)

linkedin_login: '' # LinkedIn login (Optional)
telegram_login: 'tuesday95' # Telegram login (Optional)
discords_login: 'wzrd' # DiscordS login (Optional)
steam_login: 'zopronyt' # SteamCommunity ID (Optional)
instagram_login: 'chuk.one' # Instagram login (Optional)
twitter_login: '' # Twitter login (Optional)
website_url: 'https://chuk.cz' # Website url (Optional)
cv_url: '' # CV URL (Optional)

profile_theme: 'dark' # Profile style
profile_color: 'rgb(32, 34, 37)' # Profile border color
